### ISSUE TITLE
Why Connect error handler doesn't catch `validateResponse` Error?

### ISSUE THREAD

**Issue by bebraw** [apigee-127/swagger-tools#116]
I have something weird going on in my API server. For some reason once I enable `validateResponse`, Errors don't get caught by my handler. Here's a sample:

```javascript
app.use(middleware.swaggerValidator({
    validateResponse: true
}));

app.use(function(err, req, res, next) {
    res.status(403).json({
        message: err.code,
        error: err.results.errors
    });
});
```

If you set `validateResponse` to false, the handler works.

In case you need it, I can provide a better test case. Just thought to try a lighter report in case it's something obvious.

**Comment by whitlockjc** [comment]
I think this is a timing issue.  swagger-validator's `validateResponse` wraps `res.send` so that when you actually send a payload, we validate that against your Swagger document(s).  Your error handler is likely before place in the middleware chain where the real error is being thrown.  Do you have more code to share?

**Comment by bebraw** [comment]
> Do you have more code to share?

I have the entire source available at https://github.com/koodilehto/koodilehto-crm-backend . Check `server.js` to see ordering. I deal with possible errors last but it's possible there's some error there. If you want to run it, check out `v0.1.0` tag. There are no guarantees about the stability of `master` as I'm still prototyping and figuring out how to do various things.

**Comment by whitlockjc** [comment]
Can you give me an idea of what request would create this issue, what is happening and what you expect to happen?  If your error handler above was ever working, it was by mistake or was due to errors outside of swagger-tools.  I've been wrong before of course so I'll continue looking.

**Comment by bebraw** [comment]
Hey, I set up a minimal project (subset of that big one). Unfortunately I can't reproduce the issue there so I have to continue looking. Here's the demo, though: https://github.com/bebraw/swagger-todo .

That could grow into a nice example with some effort. Add user management and jwt for auth and it's quite complete.

Anyway, I'll get back to you once I have a better test case available.

**Comment by bebraw** [comment]
I set up a test case for you. Here's how you can try it out:

1. Clone https://github.com/koodilehto/koodilehto-crm-backend
2. Check out tag `v0.2.0`
3. `npm install`
4. `npm start`
5. `npm test` in another terminal. Examine output, especially `data` part
6. Set `validateResponse: false` at `server.js`, restart server and hit `npm test` again. Now you get proper JSON.

I hope this helps.

Maybe it would be a good move to push the response validator to a middleware of its own? At least then you could push it below routing. This would eliminate the flag and maybe make the solution a bit neater and easier to understand.

**Comment by whitlockjc** [comment]
I see what is going on now and whether you like it or not, things are working as designed.  Let me explain how and we'll go from there.

What is going on is that your request fails validation and this results in an error being sent downstream to error handler middlewares.  Your 403 error handler is first in the error handler middleware chain and it is always called with the following `Error` regardless of the value of `validateResponse`:

```js
{ [Error: Parameter (body) failed schema validation]
  code: 'SCHEMA_VALIDATION_FAILED',
  failedValidation: true,
  results:
   { errors: [ [Object], [Object], [Object], [Object], [Object] ],
     warnings: [] },
  path: [ 'paths', '/invoices', 'post', 'parameters', '0' ],
  paramName: 'body' }
```

This is fully expected since your error handler is the first in the chain.  Since the request did not pass Swagger validation, the swagger-validator middleware sent the `Error` above downstream.  Working as expected.

Now, whenever `validateResponse` is `true`, the same thing happens **but** now your response fails validation.  So whenever your 403 middleware returns the JSON payload it is, that response does not pass Swagger validation and again, you get a new error which is as expected:

```js
{ [Error: Response validation failed: failed schema validation]
  code: 'SCHEMA_VALIDATION_FAILED',
  failedValidation: true,
  results: { errors: [ [Object] ], warnings: [] },
  originalResponse: <Buffer 7b 22 6d 65 73 73 61 67 65 22 3a 22 53 43 48 45 4d 41 5f 56 41 4c 49 44 41 54 49 4f 4e 5f 46 41 49 4c 45 44 22 2c 22 65 72 72 6f 72 22 3a 5b 7b 22 63 6f ...> }
```

The way I see it, things are working as expected.  If this isn't making sense or there is an error in my logic, let me know.

**Comment by whitlockjc** [comment]
Since these `Error` objects are intended for use by server authors, I've not done anything with `originalResponse` to make it more readable but its value is that of the JSON you called in your 403 handler.

Another thing worth mentioning is that I don't think your 403/404 handlers are doing what you intend.  Actually, I'm pretty sure they aren't.  All responses with your code as-is returns a 403 even when it's not a 403 but maybe a 400 (Invalid request) or a 500 (Invalid response).

**Comment by bebraw** [comment]
I figured out why it fails. Looks like it actually has something to do with field naming! I simply changed `error` to `payload` and it started giving the correct output.

Maybe this is due to some internal detail of Express or something? So strange.

You are correct in that 403 isn't the correct response code always. The error handler will need extra beefing up later on.

**Comment by whitlockjc** [comment]
This is why: https://github.com/koodilehto/koodilehto-crm-backend/blob/master/spec/definitions/error.js  Nothing to do with Express or swagger-tools, it's just that you've defined the contract for `error` to be structured one way but your response was another.  Make sense?

**Comment by bebraw** [comment]
Of course! Thanks.
