### ISSUE TITLE
swagger-security does not send errors downstream via next

### ISSUE THREAD

**Issue by bebraw** [apigee-127/swagger-tools#117]
I have set up my current version like this (yup, this needs to change):

```javascript
app.use(middleware.swaggerSecurity({
    apikey: function(req, authOrSecDef, scopes, cb) {
        if(req.headers['x-auth-token'] === apikey) {
            return cb();
        }

        cb(new Error('Failed to authenticate'));
    }
}));
```

Looks like it returns:

```json
{
  "error_description": "Failed to authenticate",
  "error": "server_error"
}
```

Is it possible to customize the format? Ideally I should be able to use the same error format as elsewhere in my API.

On a related note, is it possible to pass an api key through header via the API client (swaggerUi). It looks like it defaults to query. Of course I can change my API to the same scheme.

**Comment by whitlockjc** [comment]
It seems that swagger-security is not sending these errors downstream via `next` or I would suggest to write an error handler.  I'm going to talk to the original author to see why he chose to `res.end(JSON.stringify(err))` instead of `next(err)` and I'll get back to you.  If the second approach was used, of course you'd be able to do this:

```js
app.use(function (err, req, res, next) {
  if (err.message === 'Failed to authenticate') {
    err.message = 'Custom error for Juho: ' + err.message;
  }

  next(err);
});
```

I'll get back to you.

**Comment by whitlockjc** [comment]
I will be changing how swagger-security works.  I somehow missed that anomaly when I brought in the pull request.
