### ISSUE TITLE
Throw error if required: true is absent for path parameter

### ISSUE THREAD

**Issue by mohsen1** [apigee-127/swagger-tools#125]
For example:

```yaml
---
swagger: '2.0'
info:
  version: 1.0.0
  title: petstore
paths:
  /pets/{pet-id}:
    get:
      responses:
        200:
          description: Return all pets
          
    parameters:
      - name: pet-id
        in: path
        description: id
        type: string

```

**Comment by mohsen1** [comment]
Hey @webron should be throw an error for this spec?

**Comment by whitlockjc** [comment]
As of right now, swagger-tools validates this.  The way it works is that path parameters are implied to have `required` set to `true`.  If you set them to `false` or do not provide a parameter definition for the path parameter _(`in` of `path` and `name` matching the path parameter in brackets)_, we will generate a validation error.  If this is inaccurate and we need to validate that all path parameters are provided, with the `required` attribute explicitly set to `true` I can do that but I defer to @webron's judgement.

**Comment by webron** [comment]
Right now, it has to be explicit. I think there's only one case where there's an implicit definition, and this is not it.

There are benefits and drawbacks for both options.

IIRC, the JSON schema actually validates it, but I'll add another test in case it is missing.

**Comment by whitlockjc** [comment]
Yeah, if you don't have the `required` property, the JSON Schema validation does not flag an error.  If you can update the JSON Schema to require the `required` property, that would be a start.  You should be able to create a rule that requires the `required` value be `true` when `in` is `path` but if not, no big deal as I already validate this.

All of this being said, if the only thing not happening now is that we are assuming that for path parameters, `required` is `true` when not provided because the JSON Schema for Swagger 2.0 allows you to omit it without error, I'd say this is more an issue for swagger-spec.  Thoughts?

**Comment by webron** [comment]
Of course, if the schema allows it (and as you said, it's easy to set it as not), it's definitely a swagger-spec issue.

**Comment by whitlockjc** [comment]
Keep me in the loop.  I don't mind doing the check here but at the very least, just making `required`...required could be a start.  Even that alone would mean that swagger-tools is already doing the right thing.  If you agree, I'll close this.

**Comment by webron** [comment]
It should definitely be handled by the schema. Any chance you'd open an issue on swagger-spec? That way I could easily keep you update when it is fixed.

**Comment by whitlockjc** [comment]
Done.

**Comment by mohsen1** [comment]
👍
