### ISSUE TITLE
Middleware Error response messages changed from default JSON to HTML

### ISSUE THREAD

**Issue by jcferrer** [apigee-127/swagger-tools#133]
Error reponse for invalid token using volos redis middleware (in version 0.7.4)

{"error_description":"invalid_token","error":"invalid_token"}

Error response now with vesion 0.8.0

Error: invalid_token<br> &nbsp; &nbsp;at makeError (c:\Users\jferrer\git\cv\si\api\m\weather-swag\node_modules\volos-oauth-redis\node_modules\volos-oauth-common\lib\oauth.js:531:13
)<br> &nbsp; &nbsp;at c:\Users\jferrer\git\cv\si\api\m\weather-swag\node_modules\volos-oauth-redis\node_modules\volos-oauth-common\lib\oauth.js:470:12<br> &nbsp; &nbsp;at c:\Users\
jferrer\git\cv\si\api\m\weather-swag\node_modules\volos-oauth-redis\lib\redisruntime.js:280:26<br> &nbsp; &nbsp;at try_callback (c:\Users\jferrer\git\cv\si\api\m\weather-swag\node_
modules\volos-oauth-redis\node_modules\redis\index.js:573:9)<br> &nbsp; &nbsp;at RedisClient.return_reply (c:\Users\jferrer\git\cv\si\api\m\weather-swag\node_modules\volos-oauth-re
dis\node_modules\redis\index.js:661:13)<br> &nbsp; &nbsp;at ReplyParser.&lt;anonymous&gt; (c:\Users\jferrer\git\cv\si\api\m\weather-swag\node_modules\volos-oauth-redis\node_modules
\redis\index.js:309:14)<br> &nbsp; &nbsp;at ReplyParser.emit (events.js:95:17)<br> &nbsp; &nbsp;at ReplyParser.send_reply (c:\Users\jferrer\git\cv\si\api\m\weather-swag\node_module
s\volos-oauth-redis\node_modules\redis\lib\parser\javascript.js:300:10)<br> &nbsp; &nbsp;at ReplyParser.execute (c:\Users\jferrer\git\cv\si\api\m\weather-swag\node_modules\volos-oa
uth-redis\node_modules\redis\lib\parser\javascript.js:203:22)<br> &nbsp; &nbsp;at RedisClient.on_data (c:\Users\jferrer\git\cv\si\api\m\weather-swag\node_modules\volos-oauth-redis\
node_modules\redis\index.js:534:27)

**Comment by whitlockjc** [comment]
I don't understand.  This is a volos stacktrace.  The `0.8.0` release of swagger-tools did make it where swagger-security errors were sent downstream using Connect practices instead of returning JSON.  _(Errors are sent downstream via `next` like all middleware should.)_  If you're getting HTML now where you want JSON, you'll need a Connect error handler to intercept the error and convert it to JSON.  This is standard Connect practice documented here: http://stephensugden.com/middleware_guide/#error-handling

If you agree with my assessment, feel free to close this.  Otherwise, give me more information as to how you expect this to work so I can better understand.

**Comment by jcferrer** [comment]
I see that. On version 0.7.4 using the volos stack, oauth errors showed up as JSON by default, while cache and 
quota returned the HTML with the stack trace.

Now with v.0.8.0 all volos middleware returns the same format.

I will use then an Error handler now.

Thanks Jeremy.

JC Ferrer

**Comment by whitlockjc** [comment]
No problem.  I mentioned this in the release notes but it might not had mentioned the impact clearly.  Sorry about that.
