### ISSUE TITLE
Proposal - export (or move to a separate module) the internal objects\parameters validation mechanism that used by the validator middleware

### ISSUE THREAD

**Issue by borisirota** [apigee-127/swagger-tools#148]
This will make it usable by other projects as well. For example, it will be possible to add client side validation in the awesome [swagger-js-codegen](https://github.com/wcandillon/swagger-js-codegen) project :)

**Comment by whitlockjc** [comment]
I actually think this stuff will be going away soon.  If you look at #135, you'll see I'm already in the process of reviewing the internal/manual validation stuff because it's basically a subset of what you'd get with real JSON Schema validation.  I'm going to close this but do keep an eye out for #135 and what we do with it.  Whatever I do, I'll expose it.

**Comment by whitlockjc** [comment]
Also, if you wanted to use it right now, you can do something like this:

``js
var validators = require('swagger-tools/lib/validators');

validators.validateSchemaConstraints('2.0', someSchema, somePath, someValue);
``

**Comment by whitlockjc** [comment]
So just to summarize: You should be able to use this code already but it might change soon as a result of #135.  This is not an officially exposed API so if #135 changes it, your code might need to be updated in the future.  Also, #135 may change how much of this actually implemented in swagger-tools but the same concepts will happen because I use this to validate default values at minimum.

**Comment by borisirota** [comment]
Cool thanks !
