### ISSUE TITLE
How often is swagger-ui updated.

### ISSUE THREAD

**Issue by codeHatcher** [apigee-127/swagger-tools#149]
I need the following incorporated https://github.com/swagger-api/swagger-ui/issues/609 How long does it usually take to integrate those changes? If I wanted to incorporate those changes myself what would be the easiest way? Just change the package.json of swagger-tools? Is there a better way?

**Comment by codeHatcher** [comment]
Looking at the library I see that isn't an option.

**Comment by whitlockjc** [comment]
I haven't updated swagger-ui in a while but I will be sure to in the next release.  There is a middleware option to serve your own swagger-ui distribution instead of the bundled one so you could use that to serve the version you need until I get a new version out.  It's documented in the Middleware documentation.

**Comment by codeHatcher** [comment]
That was relatively painless. Thanks.

Is there another swagger-tools that has everything except the ui? Is there any benefit of using the bundled ui when I could just use swagger-ui separately? At least that way I could have an always up to date swagger-ui.

**Comment by codeHatcher** [comment]
Also thanks for designing it in a way that made it easy to switch out the ui.

**Comment by whitlockjc** [comment]
I should break swagger-ui and the serving of the Swagger documents into different pieces but for now, there is no way to use swagger-tools to serve only the docs and not the ui.  As for benefits, it was just a convenience.
