### ISSUE TITLE
File upload doesn't seem to be working in swagger-ui

### ISSUE THREAD

**Issue by codeHatcher** [apigee-127/swagger-tools#150]
I suspect this is because of swagger-ui but I thought I would upload it here to make everyone aware as it likely affects multiple people.

File upload fails. 

```json
          {
            "name": "file",
            "in": "formData",
            "type": "file",
            "description": "Image information",
            "required": false
          },
```
request is never made
![image](https://cloud.githubusercontent.com/assets/5360982/6203376/a6830324-b559-11e4-990c-ff730d879a9d.png)

![image](https://cloud.githubusercontent.com/assets/5360982/6203377/b3456444-b559-11e4-96ea-40fcb39bd13b.png)

**Comment by codeHatcher** [comment]
using NOT swagger-ui it works fine from a middleware perspective.

**Comment by whitlockjc** [comment]
Since it works outside of swagger-ui but fails to with swagger-ui, it sounds like a bug in swagger-ui.  There is no code for file handling in swagger-tools yet so I don't see swagger-tools tools being involved yet.  _(There is an open issue for supporting files officially but it's not implemented yet.)_
