### ISSUE TITLE
Swagger Metadata doesn't get attached to routes with trailing optional path parameters

### ISSUE THREAD

**Issue by MrLeebo** [apigee-127/swagger-tools#156]
I just want to say thanks for putting these tools together.

This is a really minor thing, but it was tripping us up on something earlier today so I figured I'd mention it. There appears to be an issue with path matching an operation in swagger-metadata. If the request leaves a trailing path parameter empty, swagger-metadata doesn't match. This leaves you with an undefined `req.swagger`.

Example Operation JSON
```js
"/sample/{num}": {
  get: {
    operationId: "foo",
    parameters: [{ name: "num", in: "path", type: "number" }],
    responses: {
      default: { description: "Success" }
    }
  }
}
```

Example Express Path:
```js
app.get(/\/sample\/(\d*)/, function(req, res) {
  res.send(req.swagger); // works for /sample/1 but not for /sample/
});
```

For the sample route above, if I request `/sample/` I would expect req.swagger to be populated, but it stays blank unless the parameter has a value.

**Comment by whitlockjc** [comment]
Path parameters are never optional in Swagger so if you do not provide the `{num}`, the path is treated as `/sample/`.  It's working as designed.

**Comment by MrLeebo** [comment]
@whitlockjc That's kind of my point. I would expect that using validator middleware to make a stink because the schema validation errors out. Instead, the metadata middleware fails to parse it so no validation ever happens. The router still handles the request though, so you end up with a request that bypasses ALL of your validations.

If I my security authorization was integrated with swagger-tools then that would have been bypassed as well...

**Comment by whitlockjc** [comment]
Here is how it works.  swagger-metadata will evaluate a request path against the known Swagger paths and if it is a known path, `req.swagger` will be created with pertinent information from Swagger.  So for example, if Swagger has a `/pets/{id}` path, `/pets/1` will be a Swagger path but `/pets/` will not be one because to Swagger, [all path parameters are required](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-7) and so since Swagger does not treat `/pets/` and `/pets/{id}` the same, swagger-tools does not either.  This means we do not treat `/pets/` as a request for `/pets/{id}`.  Since it technically is not a Swagger path, the swagger-tools middleware has no business getting involved.  Make sense?

**Comment by MrLeebo** [comment]
I think you're blurring the line between path matching logic and validation logic. If `{id}` is of type "number", should `/pets/foo` not be a valid swagger path match because foo isn't a number? Why should `required: true` be attributed to path matching but `type: "number"` isn't?

I don't disagree that path parameters are required, but I think they should be treated the same as any other validation error which is the validation middleware generates a 400 response. I certainly don't expect to get a 200 response that bypasses the rest of my validation and security middleware.

In any case whether this gets fixed or not, I'm working around the issue in my app by having extra middleware that responds to any request with a 400 if `req.swagger` is undefined.

**Comment by whitlockjc** [comment]
I'm not blurring things, this is a Swagger nuance but maybe I'm misunderstanding the problem here.  In the beginning, you said that that a request to `/sample/` was not getting the `req.swagger` metadata and I explained it's because your Swagger route is not `/sample/` but `/sample/{num}` and to Swagger, those are two separate routes with two separate definitions so omitting the first route, which you did, means a request to `/sample/` does not get processed by swagger-tools middleware because it is not `/sample/{num}`.  If this is still the case, I'm not blurring anything because while Swagger's handling of this is debatable, I'm doing things the Swagger way.  If you want to be able to pretend that the `{num}` in `/sample/{num}` is optional, you need two routes: `/sample` and `/sample/{num}`.  This is not my doing, this is how Swagger works.

Your last comment seems to be something new entirely.  If you have a `/pets/{id}` and `id` is of type `number`, if you hit `/pets/foo`, you will create a request validation exception because `foo` is not a valid number.  swagger-tools middleware handles this already.

**Comment by whitlockjc** [comment]
@MrLeebo and I discussed this a little more offline.  Basically, when using routers other than the swagger-router middleware provided by swagger-tools, you can run into a problem with the router supporting optional path parameters and Swagger not.
