### ISSUE TITLE
Match requests as if path parameters were allowed to be optional

### ISSUE THREAD

**Issue by whitlockjc** [apigee-127/swagger-tools#159]
Swagger **DOES NOT** support optional path parameters but since most, if not all, servers/routing libraries out there do, there is a disconnect when hooking up Swagger _(via swagger-tools or otherwise)_ can become problematic.  For example, let's say you have a path of `/users/{id}` and someone requests `/users`.  What should happen?  If `/pets` is a valid path, you should probably provide a separate Swagger path definition and behave that way.  But what if you want requests for `/users` to behave as if the user requested `/users/{id}` but without providing the `id` path parameter?

The purpose of this feature is to solve this problem.  The solution is to provide some metadata on the pertinent parameters to allow swagger-tools middleware to associate the `/users` request with `/users/{id}` so that the swagger-tools validation middleware will flag the request as invalid for not having provided the required `id` path parameter.

The plan is to mark path parameters with a vendor extension `x-swagger-router-optional` and then the swagger-tools middleware will mark path parameters are optional when matching requests but this **WILL NOT** mark the path parameter as optional when doing request validation as that would break the Swagger contract.  We will not break the Swagger contract no matter how much we may disagree with it.  The purpose of doing this at a per-parameter level instead of at the path level is that while simple paths may have only one path parameter, that is not a guarantee so we need to allow for per-parameter support for this annotation.

/cc @MrLeebo

**Comment by MrLeebo** [comment]
To clarify, this would be if someone requests `/users/` with a trailing slash, I think `/users` without it is legitimately a different route, it's just the trailing slash that makes it ambiguous whether they meant the path `/users` or `/users/{id}`.

**Comment by MrLeebo** [comment]
If this is going to be wrapped up in an aliasing feature then... something like this? https://gist.github.com/MrLeebo/a905ef2c2aaae203cc57

Obviously it would need to not be an error for some aliases to be missing parameters, but it should probably still trip validation if an alias had a `{foo}` param not specified in the params list.

**Comment by whitlockjc** [comment]
I'm going to take a break from this and think about it a bit more.  I'm pretty sure aliases are out because they will be too easy to abuse.  No guarantee but as it looks now, we're more looking at the original proposal for per-path parameter annotations to mark them as optional.

**Comment by whitlockjc** [comment]
This really is a Swagger limitation and I don't think we'll be supporting this at this time.

**Comment by Growiel** [comment]
Hi,

Is there any progress on this ? I need path aliases for my documentation and not having is a real pain as I have to duplicate my declaration and when I update the method, I have to update the documentation for all the aliases...

My usecase is easy:

/user [post] = /user/add [post]
/user [get] = /user/get [get]

And so on for every HTTP Verb. Basically I'm providing a "backbone-ready" way to do it with the routing depending only on the HTTP Verb (because our main clients are using backbone) and a more verbose way to do it by accessing /user/add instead of just /user/, which is more human-friendly.

Sometimes the usecase is a little more complex (this is all GET):

/blogs/{blog_id}/posts = /posts/blog/{blog_id}
/comments/user/{user_id} = /user/{user_id}/comments

We've been asked to provide entry points from both ends of relationships, so you can get the posts associated to a blog via the /blogs/ endpoint or via the /posts/ endpoint.
The PHP method called is actually the exact same one for both route, the parameters are the same, everything from a documentation standpoint is the same, except for the path.

I want to be able to either specify multiple paths for an Operation (make "path" an array ?) and/or be able to use $ref to reference another Operation, something like:

    paths:
      /user:
        post:
          // All the declaration here, with responses, parameters...
      /user/login
        post:
          $ref:#/paths/user[post]

Something like this. Right now Swagger is barelly usable for us, which is a shame because it's cool.

**Comment by whitlockjc** [comment]
You can do this right now with JSON References:

```yaml
paths:
  /blogs/{blog_id}/posts
    # ...
  /posts/blog/{blog_id}
    $ref: '#/paths/~1blogs~1{blog_id}~1posts'
```
