### ISSUE TITLE
More user friendly errors for parameters that are not conforming to schema

### ISSUE THREAD

**Issue by mohsen1** [apigee-127/swagger-tools#200]
Based on our previous discussion and [this issue](https://github.com/swagger-api/swagger-editor/issues/415) I think parameters are one of main sources of confusion in Swagger and Schema errors are not very clear what's wrong. Maybe Swagger Tools can validate each parameter based on it's `type` property and tell user what other properties it's missing or what properties are extra.

**Comment by whitlockjc** [comment]
I agree that the way Swagger 2.0's JSON Schema uses `oneOf` creates cryptic errors.  I will see what we can do.  I'm not sure this is something that can be fixed by `type` as it's basically possible for this to happen any place where Swagger's JSON Schema uses these more complex JSON Schema matchers.  We've talked about this before but at the time I didn't think there was anything we could do consistently but I might be able to come up with something.

**Comment by mohsen1** [comment]
When a response object is missing `description` a similar error appears. Responses should get the same treatment.
