### ISSUE TITLE
Support for iojs (validation middleware)

### ISSUE THREAD

**Issue by jkirkpatrick** [apigee-127/swagger-tools#202]
I've begun testing existing code with the iojs runtime. There's no legacy node_modules or other "cached" node files laying around, using a clean pull / npm install.

I tried the switch from node v0.12 to iojs v1.8.1 runtime - using either swagger-tools v0.8.5 or v0.8.6 results in basically the same behavior - I wanted to make sure it wasn't due to the JSON schema draft updates included in the most recent version. After removing swagger-tools middleware the code behaves pretty much as expected. The issues with iojs seem to be related to the validation middleware ("SyntaxError: Response validation failed" is typical, but not always the problem). 

Very simple API endpoints (hard-coded response models & values e.g. /version) work fine on both runtimes, but anything else is broken. If it's more complicated than a GET to the simplest model with hard-coded values it will fail to validate or even send a response after/during validation. Most wrapper endpoints and examples (e.g. the MSN /weather demo) are totally inconsistent in their behavior - randomly returning 404, 500, timeouts, and the occasional 200. Other urls with POST/PUT/DELETE fail entirely. Enabling mocks also causes every request to hang/timeout when the responseValidation is disabled. 

Note that these same API's are relatively stable on node 0.12 and that unit-testing also passes on both platforms - it's not until e2e testing (or using the /api-docs "try it" button or cURL) show any errors with the swagger-tools/iojs combo.

**Comment by whitlockjc** [comment]
I'm not sure why io.js would be causing an issue so I decided to run the swagger-tools test suite using io.js and it ran just fine.  I've got io.js@v1.2.0 installed and I ran `gulp` to run the node.js and browser test suites and they ran fine.  What server environment/framework are you using?  I will update the `.travis.yml` to start testing io.js explicitly but my manual tests say io.js and swagger-tools are working just fine.

To help further, I would need more information.  What server library/framework are you using?  What version of io.js are you using?  What does your server configuration that wires in swagger-tools look like?  What is your Swagger document?  _(That last one doesn't matter too much because if you're wiring things up properly, you should not be able to load an invalid document.)_

**Comment by mohsen1** [comment]
BTW you can add `"iojs"` to [this](https://github.com/apigee-127/swagger-tools/blob/master/.travis.yml#L3) array to run tests in iojs too. having node 12 there is not a bad idea either

**Comment by whitlockjc** [comment]
I mentioned that above.  :)

**Comment by whitlockjc** [comment]
Done.  I also enabled the faster, container-based tests.  :)

**Comment by whitlockjc** [comment]
I'm not seeing any failures related to io.js: https://travis-ci.org/apigee-127/swagger-tools

I don't know what else to do without more details.  If I don't hear back, I'll probably close this because I have an extensive test suite that is running just fine on io.js right now and my manual attempts at producing any anomalies on io.js has come up fruitless.

**Comment by jkirkpatrick** [comment]
Thank you and please feel free to close... I am writing some tests and will
deploy to some additional machines to try an hunt this down. If I can come
up with anything specific / actionable, I will update.

Please note that the problems do not appear until running e2e tests on
non-trivial url's - well beyond what the current test suite provides. I'm
going to use Selenium to create more comprehensive tests in order to narrow
the problem down, or at least exhibit consistent behavior.

**Comment by whitlockjc** [comment]
Please let me know if you find anything.
