### ISSUE TITLE
swagger-ui appears not to render parameters correctly

### ISSUE THREAD

**Issue by apti-tids** [apigee-127/swagger-tools#236]
When running through the /weather quick-start example and viewing the docs generated by the swagger-ui the unit parameter does not appear to render correctly.

![swagger_ui](https://cloud.githubusercontent.com/assets/5489120/8390985/be36a0ca-1ca6-11e5-84fb-87b8c27b3091.png)

If i view this same swagger document using editor.swagger.io it renders ok.

**Comment by whitlockjc** [comment]
This is technically a swagger-ui issue.  I can update the version shipped with swagger-tools but you too can run your own version of swagger-ui if you'd like: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swaggeruioptions  Also, do not confuse swagger-ui with swagger-editor, they are two completely different tools.

I'm going to close this for now since I typically update the swagger-ui shipped with swagger-tools before a release, which should be coming soon.
