### ISSUE TITLE
Parse json data with custom content type header

### ISSUE THREAD

**Issue by nikdunn** [apigee-127/swagger-tools#244]
I'm trying to us a custom content type header of:
application/vnd.onesaf.osc-v1.0+json in a message and it's failing the "application/json" check in the jsonParser in swagger-metadata.js at line 61.

Is there a way to configure swagger-tools to treat custom types as application/json?

Thanks,
Nik

**Comment by whitlockjc** [comment]
What failure are you seeing? What is happening and what do you expect?

**Comment by nikdunn** [comment]
Swagger-tools is refusing to parse the body of the request because the 
content-type header is not equal to "application/json." I'm using a 
vendor specific content type. I'd expect some way for that to work. 
Regexing out json seems a bit tacky, but it would work. Better would be 
something like jquery's ability to map formats to content types using 
the "accepts" property. I'd like to say treat " 
application/vnd.onesaf.osc-v1.0+json" as json in the body parser.

Thoughts?

Nik

**Comment by whitlockjc** [comment]
Anytime swagger-tools cannot parse the value, its vale is left as it was provided and you can then handle this yourself.  Since this is a JSON format, you might see if body-parser lets you register custom formats.  If that isn't an option, you'd have to use a custom middleware after swagger-metadata to parse this yourself and update the proper `req.swagger.params[YOUR_PROP_NAME].value` with the result.  Many if options but right now, swagger-tools only supports JSON and primitives.  I might add this feature in the future.

**Comment by nikdunn** [comment]
I'll look into that. Do you know where the value is stored when 
swagger-tools cannot parse the value? It was not obvious to me where it 
was available.

Thanks,
Nik

**Comment by whitlockjc** [comment]
Any time swagger-tools cannot parse/process the provided values, they are stored in the same place the processed value would be: `req.swagger.params[YOUR_PROP_NAME].value`.  You can also use `req.swagger.params[YOUR_PROP_NAME].originalValue`.  You can also access the `req` object directly.

**Comment by whitlockjc** [comment]
At this time, I don't see us adding specialized support for custom content parsers.  Since we give you access to the raw data to process your own way in your controller, I am going to close this.
