### ISSUE TITLE
Validation of `produces` can cause trouble with empty bodies

### ISSUE THREAD

**Issue by earth2marsh** [apigee-127/swagger-tools#255]
When I'm building an API, I'm likely to thing JSON-first, so I'll set my `consumes` and `produces` as a top-level declaration. However, there are times where a POST can return an empty body, not just an empty set of `{}` braces.

Express, for example, assigns a `Content-Type` of `text/plain` in this situation. Either swagger-tools should inject the appropriate `Content-Type`, such as `application/json`, or else it should skip `Content-Type` validation of empty bodies (or it could remove the `Content-Type` all together). One edge cases to consider is whether an `Accepts` header has been passed, in which case, it might make sense to return the Content-Type that the client has asked for with the empty body.

**Comment by earth2marsh** [comment]
One more approach would be to override the `produces` in the spec to be `text/plain`. While pedantically correct, this is an unexpected requirement and places too much burden on the designer to discover and correct the issue.

**Comment by whitlockjc** [comment]
I don't see swagger-tools ever injecting the `Content-Type` of a response as that is the responsibility of the API author.  I realize the problem here but I just don't think swagger-tools is where the fix should be.  Since the Swagger document describes how the API works, either it should be updated to reflect that the API could return `text/plain` so you don't have to update your controller to do the right thing or the controller needs to set the `Content-Type` itself.

My first inclination was to just disable validating the `Content-Type` for `void` responses and to do this would be a very simple fix.  *(**Note:** We already do not do response content validation for `void` responses because there is no schema to use to validate the response content, which happens to be nothing here.)*  But from the perspective that the Swagger document describes how an API will respond, just disabling the validation of `Content-Type` didn't feel right because it allows your Swagger document to say that it responds with a `Content-Type` of X but your API is actually returning a `Content-Type` of Y.

The whole idea of swagger-tools' response validation is to ensure that your response, all of it so not just the response content, adheres to what you've defined in your Swagger document.  This isn't about being *"pedantically correct"*, it's about ownership and none of swagger-tools' middleware ever gets involved in crafting/altering a response so I don't see it starting now.

Of course, I'll keep this open to read the rebuttal but I just wanted to explain this for those following along.

**Comment by theganyo** [comment]
Not that this is relevant to empty bodies... but I wonder where all this leaves things like 500 errors generated outside of our control? Will we always be potentially open to getting a response validation error that really only masks another error? Or is there a dictate that the Swagger must always include a generic "unknown error" definition and the app must always register an error handler to ensure that format? Or is there some other solution?

**Comment by whitlockjc** [comment]
Well, all errors are not really masked.  Sure, the "response validation" error message is the one printed whenever you rely on the default error handler but all errors introduced or encountered by swagger-tools are printed to console when [debugging is enabled](https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-middleware-debugging).  Whenever we wrap `res.end` we are wrapping the lowest-level API that handles sending responses so it's impossible to know if the response was due to some error or a route handler response.

I'm sure we can come up with something.

**Comment by whitlockjc** [comment]
The original issue is not something I think I want to budge on.

**Comment by earth2marsh** [comment]
When I'm working in a contract-first workflow, if the controller I define returns a null response, and I've declared that my operation `produces: application/json`, but then the server doesn't return `application/json` as the `Content-Type`, it is confusing to me as to why that happened. 

Is it ever a problem when a server returns an empty body under the guise of `application/json`? Perhaps Express is getting in the way? It seems to be adding the `text/plain`, which is conflicting with the contract validation. 

I can respect that swagger-tools doesn't craft/alter the response—in which case maybe this is a swagger-node rather than swagger-tools problem?

**Comment by theganyo** [comment]
Now that the registration of the json error handler in swagger node works properly, perhaps this will be less of an issue for you?

**Comment by whitlockjc** [comment]
I agree but it's your server that isn't returning the proper `Content-Type`.  You own the controller and the logic required to adhere to your Swagger contract.

**Comment by whitlockjc** [comment]
@theganyo Probably not as this is an empty response.  @earth2marsh's controller just calls `res.end();` but does not set the `Content-Type` to `application/json` but his Swagger document says the API this handler adheres to returns `application/json`.  Express' default is `text/html` and since that is not one of the valid options, there are two options:

1. Update the Swagger document `produces` where applicable to have `text/html` in it
2. Update the controller for this API to set the `Content-Type` to `application/json`

This is unrelated to error handling.

**Comment by theganyo** [comment]
Right. Ok. So we really need to decide what purpose the validate response actually serves in the context of a live API. It seems that it's a debugging tool only that one wouldn't want to turn on except at that point. Perhaps, even, it should just a warning on the server instead of an error that *ever* would be propagated to the client.

**Comment by whitlockjc** [comment]
It's definitely up for discussion.  Let me start a new thread and get others involved.

**Comment by tavlima** [comment]
Have this discussion moved somewhere else? If so, could someone point me to it, please?

**Comment by whitlockjc** [comment]
The Swagger way of doing this is that if you intend to have an empty body, you should have a response without the `schema` property set.  Right now, we're following what Swagger suggests and we didn't really talk more about it.
