### ISSUE TITLE
swagger-validator reports valid string with format="date" as invalid

### ISSUE THREAD

**Issue by asnowfix** [apigee-127/swagger-tools#268]
```
    "swagger-tools": "^0.9.0",
```

While dealing with a response, 2 dates are rejected:

```
  swagger-tools:middleware:validator   Response validation: failed +7s
  swagger-tools:middleware:validator   Reason: Failed schema validation +4ms
  swagger-tools:middleware:validator   Errors: +0ms
  swagger-tools:middleware:validator     0: +0ms
  swagger-tools:middleware:validator       code: INVALID_FORMAT +0ms
  swagger-tools:middleware:validator       message: Object didn't pass validation for format date: 2015-08-19T03:36:07.000Z +0ms
  swagger-tools:middleware:validator       path: ["result","320","lastModifiedDate"] +0ms
  swagger-tools:middleware:validator     1: +0ms
  swagger-tools:middleware:validator       code: INVALID_FORMAT +0ms
  swagger-tools:middleware:validator       message: Object didn't pass validation for format date: 2015-08-19T03:36:07.000Z +4ms
  swagger-tools:middleware:validator       path: ["result","320","submittedDate"] +0ms
```

...while they are perfectly valid according to [RFC3339 examples](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#date.and.time.format.examples) are recognized as such by Node.js:

```
> d = new Date("2014-03-18T06:46:26.000Z")
Tue Mar 18 2014 07:46:26 GMT+0100 (Romance Standard Time)
```

**Comment by whitlockjc** [comment]
Invalid formats and types are handled by [z-schema](https://github.com/zaggino/z-schema) and its logic is based off of this section of the RFC3399 spec: http://tools.ietf.org/html/rfc3339#section-5.6  I know for Swagger 1.2 support I copied the `date` and `date-time` format validators from z-schema for Swagger 1.2 support, which I had to manually validate things since Swagger 1.2 objects are not valid JSON Schema, and it uses a `RegExp` like this: `/^([0-9]{4})-([0-9]{2})-([0-9]{2})$/`  That being said, I'm not surprised your `date-time` value is not passing `date` validation but since z-schema is the one performing the validation, I'd suggest you open an issue with them if you don't agree with what I've described above.
