### ISSUE TITLE
Mock routes should set response statusCode

### ISSUE THREAD

**Issue by theganyo** [apigee-127/swagger-tools#269]
Specific case: Hapi appears to not set status code to 200 automatically (apparently the other frameworks do). Since swagger-tools validator relies on statusCode being set (`swagger-validator.js:224:41`), it should ensure that it explicitly sets statusCode when sending responses.

See: https://github.com/swagger-api/swagger-node/issues/277

**Comment by whitlockjc** [comment]
This is more of a result that `res.statusCode` does not default to some value in Hapi rather than swagger-tools not setting `req.statusCode`.  The way mocking works is that it will check `req.statusCode` and based on its value, we will look up the response for that status code.  Since Hapi does not set this, we will not assume `res.statusCode` has been set and default to `200` to fix this issue.

**Comment by whitlockjc** [comment]
Actually, mocking handles this fine.  :)  The problem with this is in the validator where we do response validation.  No biggie, the fix is still the same.

**Comment by whitlockjc** [comment]
You're right, we should be explicitly setting `res.statusCode` when we render the mock response.  Since we fail to do that, and Hapi doesn't do it for us, we break the response validation code which assume `res.statusCode` is set.

**Comment by whitlockjc** [comment]
`swagger-tools@0.9.4` has been released with this fix.
