### ISSUE TITLE
responseValidator:  value expected to be an array/object but is not

### ISSUE THREAD

**Issue by smoebody** [apigee-127/swagger-tools#271]
one call to my api generates a 301 redirect response. the function call in node looks like this:

    res.redirect(301, 'http://example.com');

my swagger-spec for this api-call looks like this:
```
      responses:
        301:
          description: "Successful request."
          headers:
            Location:
              description: "redirect URI"
              type: "string"
          schema:
            type: "string"
```
on validation i get the the following _500 Internal Server Error_:

    SyntaxError: Response validation failed: value expected to be an array/object but is not

this is because swaggerValidator thinks the response value is a model (see swagger-validator.js:91).
the schema passed to `mHelpers.isModelParameter()` to retrieve if the value is a model does not have a "type" key since its the "301" object from the swagger-spec. although the schema does not allow a "type"-key at this level. any suggestions?

**Comment by whitlockjc** [comment]
Is that the actual response definition that throws the Error because based on that, and my testing, it should validate whether or not the response is a string.  The only way `mHelpers.isModelParameter()` would think the value is a model is if it's of `type` `object` or there is no `type` in which case the default is `object`.  The `schema` you have does not fit either of these scenarios.

On a different note, I would expect a `301` to not have a `schema` attribute for its response because a `301` does not have a payload body.  When you have a response without a `schema`, it means that is a `void` response or a response with no body.

**Comment by smoebody** [comment]
yes, i think so. when i debug i see the value that shall be validated is the message generated by express i guess:

    Moved Permanently. Redirecting to http://example.com

the schema that `validateValue()` uses to retrieve whether its a model or not is 
```
{
    "description":"Successful request.",
    "headers":{
        "Location":{
            "description":"redirect URI",
            "type":"string"
        }
    },
    "schema":{
        "type":"string"
    }
}
```

although validateValue() expects to have a key `type` at the same level as `description` but thats not allowed by swagger schema specs

**Comment by whitlockjc** [comment]
That is the response definition, not the response schema.  That could explain why it's broken but why that is being chosen instead of the `schema` value above is beyond me.  Let me see if I can create a test case that reproduces this.  What surprises me is this use case is no different than the existing test cases we have already: https://github.com/apigee-127/swagger-tools/blob/master/test/2.0/test-middleware-swagger-validator.js#L634  That test tests response validation passing for a primitive *(non-object)* without issue.  Can you run this in debug mode and show me the pertinent output?  `DEBUG=swagger-tools* node app.js`  *(Change for whatever the server's entry point script name is)*

**Comment by smoebody** [comment]
i made a [gist](https://gist.github.com/smoebody/55dbf89bfeb841a56c4b) here. maybe its more explaining.

**Comment by whitlockjc** [comment]
With your gist, I get this:

```
_http_outgoing.js:335
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at Array.write (/private/tmp/testing/node_modules/express/node_modules/finalhandler/index.js:126:9)
    at listener (/private/tmp/testing/node_modules/express/node_modules/on-finished/index.js:169:15)
    at onFinish (/private/tmp/testing/node_modules/express/node_modules/on-finished/index.js:100:5)
    at callback (/private/tmp/testing/node_modules/express/node_modules/on-finished/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/private/tmp/testing/node_modules/express/node_modules/on-finished/node_modules/ee-first/index.js:93:5)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

This is due to you calling `next()` after calling `res.redirect`.  If I remove that line, I do get an error content issue but it seems to be valid.  Basically, Express is returning a `Content-Type` of `text/html` with a payload of:

```html
<p>Moved Permanently. Redirecting to <a href=\"http://example.com\">http://example.com</a></p>
```

If I update your `produces` from `text/plain` to `text/html`, the error no response validation no longer occurs and the redirect works as expected.  This is working as designed.
