### ISSUE TITLE
initializeMiddleware catches all Exceptions

### ISSUE THREAD

**Issue by connected-wwen** [apigee-127/swagger-tools#276]
using swagger-tools v0.9.4,
```
// Initialize the Swagger middleware
swaggerTools.initializeMiddleware(swaggerDoc, function (middleware) {
  // gets caught silently
  throw "ABC"
});
```
found that the __initializeMiddleware__ method catches all exceptions. 

what if something goes wrong inside the swagger router controller? 
```
      app.use(swaggerMiddleware.swaggerRouter(
        {
          controllers: 'app/controllers',
          useStubs: process.env.NODE_ENV === 'development' ? true : false // Conditionally turn on stubs (mock mode)
        }
      ));
```

**Comment by whitlockjc** [comment]
Can you give me a reproduction?  We have unit tests that explicitly rely on `initializeMiddleware` throwing exceptions and they are passing.  The only thing `initializeMiddleware` should be doing, and this is tested, is when we validate your Swagger document we will `process.exit` if validation fails because there is no benefit to starting a server with invalid Swagger.  As for errors happening in the middleware, we also have tons of tests for this as well so I will need a reproduction scenario.

**Comment by connected-wwen** [comment]
A little embarrassed - it was my problem. I wrapped the ```initializeMiddleware``` function inside ```json-refs``` "resolve" ```promise``` ```then``` block and did not use a ```catch``` so it got caught silently... A ```promise``` newbie problem.

**Comment by whitlockjc** [comment]
No sweat.  :)
