### ISSUE TITLE
More details on invalid request with empty body

### ISSUE THREAD

**Issue by adrien-candiotti** [apigee-127/swagger-tools#281]
Hi,

When I send an empty/incomplete body to my api the swagger-validator middleware gives me back a nice output but there is no way to know which field are missing : 

This is an example of what i receive:
```
"status": "error",
"message": {
  "errors": [
    {
      "code": "OBJECT_MISSING_REQUIRED_PROPERTY",
      "message": {
        "type": "string",
        "description": "A description"
      },
      "path": [],
    },
    {
      "code": "OBJECT_MISSING_REQUIRED_PROPERTY",
      "message": {
        "type": "integer",
        "description": "Another description"
      },
      "path": [],
    },
```

I monkey patched the answer to add the field names to each error but I would rather have a path or field name.
If I can do anything to help please let me know.

**Comment by whitlockjc** [comment]
Without your operatoin schema, I can't tell who is wrong so you'll need to post that.

**Comment by adrien-candiotti** [comment]
I created a mini app to illustrate the problem.
Here is a link to the repo: https://github.com/adrien-candiotti/validation-issue

As you will notice if you do a simple post with no body on the /example route : 
- the field names are not present in the validation results
- the possible enum values are not present in the error

**Comment by whitlockjc** [comment]
Whenever I run your example, I get this:

```
{
    "errors": [
        {
            "code": "OBJECT_MISSING_REQUIRED_PROPERTY",
            "message": "Missing required property: gender",
            "path": []
        },
        {
            "code": "OBJECT_MISSING_REQUIRED_PROPERTY",
            "message": "Missing required property: age",
            "path": []
        },
        {
            "code": "OBJECT_MISSING_REQUIRED_PROPERTY",
            "message": "Missing required property: name",
            "path": []
        }
    ],
    "warnings": []
}
```

The name of the missing property is in the `message` portion of the error.  The reason `path` is `[]` is because the error lies at the root of the object.  It wouldn't make sense to have `['name']` because you didn't supply the `name` attribute and so it can't be the source of the issue.  The way I see it, swagger-tools is doing the right thing.  If you think otherwise, the issue really is with [z-schema](https://github.com/zaggino/z-schema) because it is the JSON Schema validator I'm using.
