### ISSUE TITLE
Update version of swagger-converter

### ISSUE THREAD

**Issue by oliverhr** [apigee-127/swagger-tools#302]
Update to 1.0.1

**Comment by mohsen1** [comment]
version 1.0 has breaking API changes.

**Comment by whitlockjc** [comment]
Anyone mind sending a PR for this?  I haven't kept up with swagger-converter and since it's got breaking changes, it might make sense to have someone else do this.  *(I'm capable, just wanting to avoid the extra round trips.)*  /cc @IvanGoncharov

**Comment by IvanGoncharov** [comment]
Problem is that you need to change CLI.
Previously you just specify bunch of files.
And in new version you need to match paths inside resourceListing and actual sub-resources referenced by them.
So it required to design new CLI syntax.

**Comment by IvanGoncharov** [comment]
See [this](https://github.com/apigee-127/swagger-converter/commit/c3891d8c8bcd9be28843034bc09d14a09cd2b0fe) commit.

**Comment by whitlockjc** [comment]
I don't see a good way to do this so I don't see it happening.  The API changes make it very difficult because either the CLI caller needs to know the order and use that or there needs to be some consistent way to *guess* the paths based on the file names.

**Comment by mohsen1** [comment]
Maybe we can default to guessing paths based on file names and have the option to specify it explicitly. That way we can keep it backward compatible. I'm not sure how the arguments lists should look like though...

**Comment by whitlockjc** [comment]
Yeah, that's the rub.  I'll give it some thought.

**Comment by IvanGoncharov** [comment]
@whitlockjc I added [new function](https://github.com/apigee-127/swagger-converter#listapideclarations-function) which provide list of resourceListings with path to them. You can pass file path instead of URL as first argument and then function will also produce file paths. So you make CLI command which with `resourceListing` as first argument and path to resourceListings as second.

Note: `resourceListing` can have `basePath` which can affect result. So good idea is to remove `basePath` before passing it to `listApiDeclarations`.
