### ISSUE TITLE
Swagger Router preflight requests

### ISSUE THREAD

**Issue by l-ko** [apigee-127/swagger-tools#310]
Getting error for each route while using cross origin requests:
```Route defined in Swagger specification (/route) but there is no defined options operation.```

How to properly handle preflight requests? Do I need to define it for each route?

**Comment by whitlockjc** [comment]
The reason you are getting this error is because you do not have an `options` operation defined in your Swagger.  In most situations, people use a CORS library to handle things like this so with `ignoreMissingHandlers` and a CORS library, you should be good to go.  If you do not want to use a CORS library, you would need to add the `options` operation to your Swagger document and wire up a corresponding handler to do the real work.

**Comment by whitlockjc** [comment]
Since this is outside the scope of swagger-tools, as it is doing the right thing as it knows, I am closing this but I will continue fielding questions to help you get beyond this.

**Comment by l-ko** [comment]
Thanks, it works normally with the CORS library.

**Comment by whitlockjc** [comment]
Great new!  Let me know if I can help further.
