### ISSUE TITLE
Conflict in handler names (middleware/swagger-router.js)

### ISSUE THREAD

**Issue by frinux** [apigee-127/swagger-tools#314]
Reproduced using swagger-codegen, it seems the name of handler in swagger-router.js middleware is wrong.

In https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-router.js#L88 :

    Line 53: handlerName = req.swagger.operation.operationId;
    Line 88: var handlerId = controllerName + '_' + name;

The situation is I now have a controller Modules.js with a function doGetModulesByGet(), and the handler list is filled by names prefixed by the name of the controller.

Example: 

    handlerCache = {Modules_doGetModulesUsingGET: [Function: doGetModulesUsingGET]};
    handlerName = doGetModulesUsingGET

The result is: 

    Error: Cannot resolve the configured swagger-router handler: doGetModulesUsingGET
    at swaggerRouter (/Users/francois/Sources/Divers/swagger-codegen/microservices/modules-manager/node_modules/swagger-tools/middleware/swagger-router.js:414:18)
    at call (/Users/francois/Sources/Divers/swagger-codegen/microservices/modules-manager/node_modules/connect/index.js:239:7)
    at next (/Users/francois/Sources/Divers/swagger-codegen/microservices/modules-manager/node_modules/connect/index.js:183:5)
    at /Users/francois/Sources/Divers/swagger-codegen/microservices/modules-manager/node_modules/swagger-tools/middleware/swagger-validator.js:350:30
    at /Users/francois/Sources/Divers/swagger-codegen/microservices/modules-manager/node_modules/async/lib/async.js:52:16
    at /Users/francois/Sources/Divers/swagger-codegen/microservices/modules-manager/node_modules/async/lib/async.js:361:13
    at /Users/francois/Sources/Divers/swagger-codegen/microservices/modules-manager/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/Users/francois/Sources/Divers/swagger-codegen/microservices/modules-manager/node_modules/async/lib/async.js:236:30)
    at _asyncMap (/Users/francois/Sources/Divers/swagger-codegen/microservices/modules-manager/node_modules/async/lib/async.js:355:9)
    at Object.map (/Users/francois/Sources/Divers/swagger-codegen/microservices/modules-manager/node_modules/async/lib/async.js:337:20)

**Comment by whitlockjc** [comment]
Just to be clear, answer these:

1. What do you expect to happen?
2. What is happening?

It's hard to tell what is going on.  I assume that swagger-codegen creates a swagger-node project but I don't use swagger-codegen so I'm not sure.  As for the `options.controller` for the swagger-router middleware, it's documented here and that might explain a little: https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swaggerrouteroptions

**Comment by frinux** [comment]
I expect the handler names in handlerCache (populated in handlerCacheFromDir) to contains the right handler names. Instead of 
    handlerCache = {Modules_doGetModulesUsingGET: [Function: doGetModulesUsingGET]};
I want to have 
    handlerCache = {doGetModulesUsingGET: [Function: doGetModulesUsingGET]};

**Comment by whitlockjc** [comment]
If you do not like the generated names, you need to build the `options.controller` object yourself.  As documented, if you provide a string or an array of strings, we will generate the names for you based on the controller file name and the exported function.  If that is not what you want, you will need to pass in `options.controllers` as an object with the keys/values you want.  It shouldn't be hard.

Also, the reason it's not working as-is is because you're not using `x-swagger-router-controller: Modules` in your Swagger document.  swagger-router was built around this and if you don't want to use it, we provide a raw approach *(the `options.controller` value as an object)*.

**Comment by frinux** [comment]
Thanks for your answer, I dug deeper in the code to understand what you are explaining.

That's right, I will use the possibility to give a ```options.controller``` object to get to what I want.
The use of ```x-swagger-router-controller``` is quite intrusive for my case, so I will avoid it.

I gladly close this issue

**Comment by whitlockjc** [comment]
What's intrusive about it?  I've pondered getting rid of it all together and to just use the `operationId`.  *(See #221)*

**Comment by jookshub** [comment]
Hi, I came across this issue as I did get the same error just by trying to get the petstore-example running as a node.js server on my localhost.

Using the `options.controller` object approach by manually populating it with a key/value object of the api seems to add quite an overhead, even if one would build a function to generate this object.

My quick solution to get the Demo running was this:

    if (_.isPlainObject(controller)) {
          _.each(controller, function (value, name) {
            var handlerId = controllerName + '  _' + name,
                handlerName = name;

            debug('      %s%s',
                  handlerId,
                  (_.isFunction(value) ? '' : ' (not a function, skipped)'));

            // TODO: Log this situation

            if (_.isFunction(value) && !handlerCache[handlerName]) {
              handlerCache[handlerName] = value;
            }
          });
        }

Originally the `handerCache` had `handlerId` as the key, which resulted in the issued error.

So for what reason is this `controllerName_` added, when this breaks the default node.js example on localhost usage?

**Comment by whitlockjc** [comment]
Yes, the overhead is there but only because you're working around the way things should work, by design and as documented.  As for the swagger-codegens default example application not working, that's more of a swagger-codegens issue.

**Comment by jookshub** [comment]
Thank you for the Info, it helped to guide my investigation in the right direction.

I've found, that the swagger-editor from gitHub and the one on editor-swagger.io don't have the `x-swagger-router-controller` included in their examples. (In case anybody else is wondering)

However, by using `swagger-node` and creating a project like the `hello_world` example, it does add the `x-swagger-router-controller` into the spec.

Further, if I understood correctly, you add the `controllerName_` before `name`, because the `operationId` has to be unique across multiple controllers and this is a way to assure it, right?

So another way to solve this, is to add the `controllerName_` to the `operationId` inside the spec file.

Hope this helps somebody who is wondering, I'll suggest to fix this in the examples, as not working examples are just frustrating ... a great project, though!

**Comment by whitlockjc** [comment]
So, by default swagger-router will crawl a directory of controllers and create a mapping like this: `{Controller_Name}_{Controller_Method}`.  For example, if I had `controllers/Users.js` and it exposed a `login` function, its controller id would be `Users_login`.  If you want to wire an operation, using swagger-router, to that controller method, you'd need to use `x-swagger-router-controller: Users` and have `operationId: login`.  This is how the mapping works by default and this was how the swagger-router middleware was intended to work.

#218 made it where you could do `operationId` only based mapping so that you do not need `x-swagger-router-controller`.  That being said, the combination of `[x-swagger-router-controller]_{operationId or HTTP method}` is the mapping defined in your Swagger document and it must match the mapping created by swagger-router, as mentioned above, or the manually created mapping allowed by passing `options.controllers` as an `Object` to the swagger-router middleware.

Does this make sense?  I'd be glad to explain this more thoroughly if [the documentation](https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-20-1) is not self-explanatory.
