### ISSUE TITLE
swagger tools editor - Not as full featured as swagger.io editor???

### ISSUE THREAD

**Issue by barlowm** [apigee-127/swagger-tools#319]
I'm working through the [QuickStart](https://github.com/apigee-127/swagger-tools/blob/master/docs/QuickStart.md) example, and after creating the simple project to get the API up and running (`swagger project create simple`), I opened the editor (`swagger project edit`) and then tried to import the "Simple Weather API" listing that you have (which is in JSON format) into the editor but can't. There's no options to open or import any file.

I finally managed to get the JSON example as a YAML file (I went to the online editor `http://editor.swagger.io/#/` and imported the Weather API JSON file I'd manually created and exported that as a YAML file.
After which the normal `swagger project edit` brought up the "Simple Weather API" file just fine.

So, is there a simpler way to open (or import) an existing JSON file into a project? Or can the project editor convert to/from JSON/YAML?

**Comment by whitlockjc** [comment]
swagger-editor has a feature to import JSON using _"Paste JSON..."_.  It would be under the _File_ menu when you run `swagger project edit`.  I could convert the Swagger 2.0 example to YAML to make this simpler as well but the first answer should work too.

**Comment by whitlockjc** [comment]
If that works, feel free to close this.  The JSON examples in swagger-tools predate official YAML support for Swagger 2.0 and are not expected to work with swagger-node as-is.

**Comment by barlowm** [comment]
Well the online swagger-editor does, but when running `swagger project edit` I don't see a "File" menu, which is my confusion (I actually did use the editor file import feature on the `http://editor.swagger.io/#/` site):
![image](https://cloud.githubusercontent.com/assets/2439008/12308642/5393c9ee-ba14-11e5-96ce-80fe20c096ae.png)

**Comment by barlowm** [comment]
BTW, I'm running on Windows 7 using Chrome version 47.0

**Comment by whitlockjc** [comment]
Ah.  So it looks like the swagger-editor bundled with swagger-node does not allow this feature.  The reason being is that it is intended to work with the on-disk file only, the one created in your swagger-node project.  I'm afraid this is a swagger-node design feature and there is no working around it.  Feel free to file a bug with the swagger-node project to request the ability to support importing JSON/YAML files.

Since this is not a swagger-tools issue, I'm going to close this.  I can help make things easier for you by transitioning the 2.0 example in this project to use YAML instead of JSON but that's the best I can do.  *(I also wonder how important it is since there are online tools to convert between JSON and YAML.)*

**Comment by barlowm** [comment]
@whitlockjc Thanks, I didn't realize that the problem was with the swagger-node project code.

**Comment by whitlockjc** [comment]
No problem.  The problem here is that swagger-node bundles swagger-editor and the way it does it ends up with a slightly modified version of swagger-editor that turns off the feature you need.  editor.swagger.io has it but not swagger-node.  That's why I suggested opening the issue there.
