### ISSUE TITLE
Response validation hooks after etag generation in some cases

### ISSUE THREAD

**Issue by mnahkies** [apigee-127/swagger-tools#320]
If I have a response handler like this:

    function(req, res, next) {
        res.status(200).send(JSON.stringify({my: 'response'}));
        res.end();
    }

If the browser already has the etag for this response in it's history, and something changes to cause the response to no longer pass the swagger response validation (eg: in early dev when things are still quite fluid) then the browser will not get the validation error response.

As far as I can tell, this is because the etag is generated during the .send() and the validation doesn't hook in until .end()

A workaround is to instead do this:

    function(req, res, next) {
        res.status(200);
        res.end(JSON.stringify({my: 'response'}), 'utf-8');
    }

**Comment by whitlockjc** [comment]
swagger-tools already has code to not do validation for a `304` which is what should be returned when the content on the server is not modified.  We have tests for this as well.  What web framework are you using?

**Comment by mnahkies** [comment]
I'm using express.

The easiest way to replicate the issue it is to have a response that is valid as defined by the swagger document, request this in chrome to get it into the browser's cache, then alter the swagger document such that the response is no longer valid (and restart the node service).

If you then refresh the page in chrome, you will see the original response, whilst in your service logs you will see errors (assuming you are logging when validation errors occur).

It's somewhat of an artificial situation, but seems like a common thing to happen during early development stages. I also raised the issue in part because I wondered if there might more subtle problems arising from this.

**Comment by whitlockjc** [comment]
I believe you that this is an artificial situation.  I don't see how the swagger-validator middleware can do any better since it doesn't actually generate the response.  What is happening, that I can tell, is that the swagger-validator is doing the right thing.  It is rendering a validation error since the new Swagger schema makes the previously good response bad.  Why your browser application doesn't use this response and instead uses the cached browser response is outside the control of swagger-tools and its middleware.

If the swagger-tools middleware is doing the right thing, which it appears to be doing, I'm not sure what else to do.

**Comment by mnahkies** [comment]
swagger-tools middleware hooks to the end method of response: https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-validator.js#L170-L176

This means that when you send the response using the express send method, this code is executed first: https://github.com/strongloop/express/blob/master/lib/response.js#L179-L189 generating the etag based on the response before it is intercepted and replaced by the swagger-tools validation failed response.

I think that when a response validation error occurs that the middleware should either clear any ETag header that is set on the response, or alternatively generate it's own ETag based on the new response.

**Comment by whitlockjc** [comment]
I could do that *but* that's really up to the API author.  I personally think that swagger-tools' middleware should do nothing more than Swagger integration.  This to me is an API decision and I think it should live with the API author.  Thankfully, swagger-tools middleware has a [consistent way of handling errors](https://github.com/apigee-127/swagger-tools/blob/master/docs/Middleware.md#swagger-middleware-errors) so addressing this yourself is pretty simple:

```js
app.use(function(err, req, res, next) {
  if (err.validationFailed) {
    res.removeHeader('etag');
  }
});
```

Give this some thought and if you agree, please close this.  If not, I'm up to discuss it further.

**Comment by mnahkies** [comment]
I like that solution, and agree that it should be up to the api author. However, after doing some more digging, it seems that some of my earlier stipulations were incorrect, and that solution won't work.

The swagger validation doesn't actually fail in the 304 case, because express strips out the content type and response body before it calls the end method: https://github.com/strongloop/express/blob/master/lib/response.js#L192-L197

This means that the validation middleware doesn't receive anything to validate and so it can't tell the difference between a valid and invalid 304, so it has to assume it is valid. I can't think of any way of avoiding this that wouldn't be overly express specific.

**Comment by whitlockjc** [comment]
There is no invalid 304 as a 304 does not have a body.  swagger-tools actually skips response validation when the status code is 204 or 304 because they do not have bodies.  I do think the solution above will work *but* I can also see some chicken/egg situation where you might want to do more prior to swagger-tools response validation fires.  In that case, you can also solve that with middleware.  I'm all ears on how I can make this better.
