### ISSUE TITLE
Adding a easier way to access to params [Question ~ Request]

### ISSUE THREAD

**Issue by midudev** [apigee-127/swagger-tools#345]
Working with swagger-tools I've found, on my opinion, that is too convoluted access to request params. I've added a manual middleware to deal with it and, so far, I'm pretty happy with the result.

``` javascript
    // Add an easier way to get params from swagger-tools
    app.use((req, res, next) => {
      function getParam (param) {
        if (req.swagger.params[ param ]) {
          return req.swagger.params[ param ].value
        }
      }

      req.getParams = () => {
        var obj = {}
        for (let param in req.swagger.params) {
          obj[param] = getParam(param)
        }
        return obj
      }
      req.getParam = getParam
      next()
    })
```

My question is, how are you dealing with this? Have you found another way to easily access the params?  Would it be a good idea to add something like the middleware above in order to add a better way to access the value of the params to swagger-tools? Any feedback? Thanks for your awesome work!

**Comment by whitlockjc** [comment]
I agree it's a lot to type.  The new middleware I'm using to replace swagger-tools will not have this issue as everything is via an API: `operation.getParameter(name, [location])`.  I don't see me fixing this in swagger-tools since I'm deprecating it *(#335)* soon but I will keep it open just in case.

**Comment by miduga** [comment]
Oh boy, so swagger-tools are being deprecated? :cry: I'll keep an eye open to the new library then. :) Thanks!

**Comment by whitlockjc** [comment]
Deprecation is such a strong word.  ;)  swagger-tools is being broken up into specific modules, instead of one module containing everything *(API, CLI, Middleware, ...)*.  During this time we're taking a step back and rewriting the pieces based on all of the information we have now and releasing `1.0.0` versions for each component.  Make sense?

**Comment by miduga** [comment]
Yeah, sure, it makes sense! :+1: But it was you the first to mention the word deprecating! :stuck_out_tongue: I would say that's a fantastic idea to separate the modules and I hope to see a great evolution of the new modules. As we're going to build an API using swagger-tools at our company I'll try to be up to date on the ongoing development and try to give a hand. :)

**Comment by whitlockjc** [comment]
Don't worry, there will be plenty of documentation on migrating from swagger-tools to whatever comes after it.

**Comment by miduga** [comment]
Fantastic. Thanks @whitlockjc

**Comment by jvivs** [comment]
@Whitlockjc what github org are the individual modules being rewritten under? Or is there a roadmap listed somewhere? I'd like to help move things forward.

**Comment by whitlockjc** [comment]
Right now here are the projects:

* API: https://github.com/apigee-127/sway
* CLI: https://github.com/whitlockjc/swagger-lint *(unreleased)*
* Middleware: https://github.com/whitlockjc/sway-connect *(unreleased)*
