### ISSUE TITLE
Validating the x-"pattern_fields"

### ISSUE THREAD

**Issue by srinivascodes** [apigee-127/swagger-tools#389]
I am trying to put some restrictions on the patterned objects(that start with x-) like for e.g **x-apiId** the valid value should be alphanumeric pattern like [a-z][1-9][a-z]. Where should I make the changes so that when I type in the editor it should give me error if I missed this field and also if I entered wrong value in this field? What are files where changes are required to make this possible? I have found files like schema.json, validator.js where I think changes will be require etc. Please kindly let me know.

**Comment by whitlockjc** [comment]
I agree this is a good idea but I don't see this happening in swagger-tools.  [sway](https://github.com/apigee-127/sway) already provides this and it is the successor to swagger-tools' API, including its validation.  Per #335, we will be ceasing feature additions in swagger-tools and instead will do this in sway and sway-connect.  Since this work is already done in sway, I will close this issue.
