### ISSUE TITLE
The thrown Error in async controller cannot be caught in router middleware

### ISSUE THREAD

**Issue by winguse** [apigee-127/swagger-tools#393]
An async controller, something like this:

```javascript
export const helloWorld = async (req, res) => {
  if (Math.random() < 0.5) throw new Error('by design random error')
  return res.send('hello world')
}
```

The error will not be caught in [swagger-router.js#L408](https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-router.js#L408).

For my understanding, the root cause is, the `async` keyword make the controller returning a `Promise` actually, and any thrown `Error` will occurs out of this try-catch stack.

And I come out a walk around, it's to wrap the async controller like this to ensure the error can be processed in the later middleware chain:

```javascript
import isPromise from 'is-promise'

export const controllers = { /* async controller stuffs */ }

export default Object.keys(controllers)
  .reduce((syncControllers, operationId) => {
    syncControllers[operationId] = (req, res, next) => {
      const result = controllers[operationId](req, res, next)
      if (isPromise(result)) {
        return result.catch(next)
      }
      return result
    }
    return syncControllers
  }, {})

```

And my idea or suggestion is, I think it's good to have the logic inside `swagger-router.js`. And for further steps, the best choice is to enable full support for async controller.

**Comment by whitlockjc** [comment]
The link link you point is the error handling we have in place to handle errors that are thrown, which should typically only be unhandled exceptions, so that the error would be logged and sent downstream via `next`.  _(Handled exceptions should be sent downstream using `next`.)_  If your code never throws an error, of course that code won't be used.  Your Promise needs to pass the error it catches to `next` just like all other Connect middlewares.  I don't see us turning the handlers into promises or supporting them explicitly because Connect middleware has a well-known pattern in place that works with both async and sync code.  Since swagger-tools middleware is connect-based, you need to update your Promise usage to adhere.

Feel free to reopen this if I missed something, and we can always continue the discussion regardless.

**Comment by winguse** [comment]
Hi @whitlockjc , thanks for reply.

One thing I am not quite understanding is:

> Connect middleware has a well-known pattern in place that works with both async and sync code.

In my understanding, both `connect` and `swagger-tools` are written in ES5 standard, but in my project, I am writting in ES2016 standard. All my project's code will be translated to ES5 using babel, and keyword `async` decorated function will turn into a function returning a `Promise`. If I throw `Error` in the `async` decorated function, it cannot be caught.

* Is that because I am not in correct way to implement my async controller?
* Or do you think it's recommended to resolve it using my walk around above?

Thanks very much!

**Comment by whitlockjc** [comment]
Using ES6 within the confines of Connect middleware isn't hard but when using it, it doesn't let you change the paradigm that Connect expects.  This means you can't just expect to write or interact with Connect-based middleware and just make these functions whatever you want.  So returning Promises doesn't do anything with respect to Connect middleware as Connect doesn't understand how to use Promises.  Here is a good example of using Promsies, Generators and ES7 within Express _(follows the Connect-based middleware paradigm)_: https://strongloop.com/strongblog/async-error-handling-expressjs-es7-promises-generators/  This link not only shows you how to do this manually but even shows how you can write a solid generator.

I hope this makes sense.  Please let me know if I can help further.

**Comment by winguse** [comment]
Thanks @whitlockjc , I learnt a lot from you!

**Comment by whitlockjc** [comment]
Happy to help.
