### ISSUE TITLE
Swagger validator does not work with anchor variables.

### ISSUE THREAD

**Issue by fastcodejava** [apigee-127/swagger-tools#426]
I have scheme defined in the Swagger as:

    swagger: "2.0"
    x-a127-config:
       schemes: &SCHEMES CONFIGURED

`scheme: *SCHEMES`

When I run `swagger-tools validate swagger.yaml` I get this error  which is wrong.

    API Errors:

    #/schemes: Expected type array but found type string

    1 error and 0 warnings

I have it defined in `dev.yaml` as an array as:

    schemes:
      - https
      - http

But I still get this error​.

**Comment by SameerSiddiqui** [comment]
Seems like to be a valid issue!

**Comment by whitlockjc** [comment]
I cannot reproduce this.  Not only do all of our test documents have the `schemes` property _(as an array of strings)_ but when I tested with a minimal Swagger document, `swagger-tools validate` works as expected:

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
schemes:
  - http
  - https
paths:
  /:
    get:
      responses:
        200:
          description: OK
```

Feel free to reopen this with a real example where this issue is reproducible.

**Comment by SameerSiddiqui** [comment]
I think he mean't that when he points the scheme from config file instead of just writing them within the swagger.yaml. In your example you have 

schemes:
  - http
  - https

but he has

schemes: *SCHEMES

and this *SCHEMES is in config file. May be this is not swagger error and it is a-127 issue.

Thanks,
Sameer

**Comment by whitlockjc** [comment]
Ah, so YAML anchor support.  The YAML parser we use allows anchors but since anchors are based on the current document, and are part of pre-processing, I don't see how this could work in a Swagger document.  Maybe if you gave me a specific example that you expect to work, I could run through it.

**Comment by jcferrer** [comment]
I need more details on this one. I have no idea what you guys are talking about.

JC Ferrer

**Comment by whitlockjc** [comment]
It seems the OP is trying to use YAML anchors as a way to reuse things.  While Swagger itself says that it does not support these, I don't see why they won't work.  I just don't have enough details to repeat the issue.

**Comment by fastcodejava** [comment]
We use `YAML` anchors as lot and it does work. Only `swagger-tools validate swagger.yaml` is wrongly reporting an error.

**Comment by whitlockjc** [comment]
Will you please just give me an example document that reproduces this?  I know YAML anchors work, it's part of the YAML specification so any YAML parser should support it.  _(In fact, I verified that the YAML parser we're using, https://github.com/nodeca/js-yaml, supports it.)_  Without an example, I cannot help you.

Just to make sure I've gone above and beyond with what little you've given me, I have tested the following scenario without issue:

**swagger.yaml**

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
schemes:
  $ref: './types.yaml#/otherSchemes'
paths:
  /:
    get:
      responses:
        200:
          description: OK
```

**types.yaml**

```yaml
schemes: &SCHEMES
  - http
  - https

otherSchemes: *SCHEMES
```

**Resolved Result**

```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
schemes:
  - http
  - https
paths:
  /:
    get:
      responses:
        '200':
          description: OK
```

This seems to be working fine.

**Comment by whitlockjc** [comment]
Here is yet another example that works just fine:

**swagger.yaml**

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
x-config:
  schemes: &SCHEMES
    - http
    - https
schemes: *SCHEMES
paths:
  /:
    get:
      responses:
        200:
          description: OK
```

**Resolved Result**

```yaml
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
x-config:
  schemes:
    - http
    - https
schemes:
  - http
  - https
paths:
  /:
    get:
      responses:
        '200':
          description: OK
```

**Validation Results**

```
~/workspaces/personal/swagger-tools/bin/swagger-tools validate test.yaml -v

Validation Details:

  Swagger Version: 2.0
  Swagger file: test.yaml

Swagger document is valid
```

So as you can see, I am unsure how you are running into the problem you are.  YAML anchors appear to be fine and in fact, swagger-tools doesn't care if you use them or not and it should have no impact on validation because the YAML processing happens prior to swagger-tools being involved.

So without some sort of concrete example that can be used to reproduce this, I cannot help as all of the examples I've used above are working without issue.

**Comment by SameerSiddiqui** [comment]
This way it's failing 

**swagger.yaml**
```
swagger: "2.0"
x-a127-config:
  schemes: &SCHEMES CONFIGURED
schemes: *SCHEMES
```

**test.yaml**

```
schemes:
  - https
  - http
```

Are we doing it wrong ? 

Thanks,
Sameer

**Comment by whitlockjc** [comment]
I think you're doing it wrong.  The `SCHEMES` anchor has a value of `CONFIGURED`, which is a string.  I gave two examples above that _do_ work, one using a single document and another using JSON References to reference a value in another document.

**Comment by fastcodejava** [comment]
As @SameerSiddiqui said we have it configured correctly. We start the app with DEBUG=* NODE_ENV=test npm start.
It picks up the configuration file at runtime. Is that why Swagger tools is not working in this situation?

**Comment by whitlockjc** [comment]
What is the value of `CONFIGURED`?  Is it the real value in your document or is it a placeholder?  If it's the real value, and this seems to be backed up by the error you're seeing, your `SCHEMES` anchor is set to a string with a value of `CONFIGURED`.  Notice how your version that doesn't work is different than the _swagger.yaml_ example here: https://github.com/apigee-127/swagger-tools/issues/426#issuecomment-246836166

**Comment by fastcodejava** [comment]
I thought `**CONFIGURED**` means it is configured somewhere in a configuration, not literally `CONFIGURED`. 
And it is working for us that way as @SameerSiddiqui said. 
Is that why Swagger tools getting confused?

**Comment by whitlockjc** [comment]
swagger-tools isn't confused, it's validating the YAML based on what _you_ have provided.  `CONFIGURED` is not some special value so based on your example YAML, your `SCHEMES` anchor is literally the string `CONFIGURED`.  Since Swagger expects an array of strings for `schemes` property and you're setting it to a string value _(`CONFIGURED`)_, your document is failing validation.  Your document fails validation because your document is wrong, not because swagger-tools is confused.

I'm not sure how else to explain this but this isn't a swagger-tools issue, it's behaving as expected because you're using YAML anchors wrong.  Let's give this one more shot.

### Your Current Approach

**swagger.yaml**

```yaml
x-a127-config:
  schemes: &SCHEMES CONFIGURED
schemes: *SCHEMES
```

With this document, the value of `schemes` is `CONFIGURED`, where `CONFIGURED` is a literal string.

### The Proper Approach

```yaml
x-a127-config:
  schemes: &SCHEMES
    - http
    - https
schemes: *SCHEMES
```

With this document, the value of `schemes` is an array of strings: `['http', 'https']`

**Comment by SameerSiddiqui** [comment]
Correct! I removed CONFIGURED and the validation passed.  

Thanks,
Sameer

**Comment by fastcodejava** [comment]
Yeah even though we have `CONFIGURED`  a127 still starts. I guess it ignores certain validation errors and replaces the `schemes` with the values in the configuration file.
