### ISSUE TITLE
swagger-node vs swagger-tools

### ISSUE THREAD

**Issue by khalidx** [apigee-127/swagger-tools#449]
Which tool is the community supposed to be rallying behind? swagger-tools seems to be more recently updated but swagger-node is what is listed on the swagger.io tools page.

The swagger-node GitHub README says that it is derived from swagger-tools, but there are many differences. I've noticed that swagger-node does not include support for swagger-ui, while swagger-tools has it out of the box.

I would really appreciate some direction on this matter, thank you!

**Comment by khalidx** [comment]
@whitlockjc I see that you are pretty active in this repo, and that you represent apigee. I was wondering if you could elaborate on this.

**Comment by whitlockjc** [comment]
`swagger-node` is abstracted enough for me to not know if `swagger-tools` is still used but from what I can tell, `swagger-node` _does_ use `swagger-tools`' middleware.  But since `swagger-node` is a wrapper around `swagger-tools`, it's not required or guaranteed to expose all of it, like `swagger-ui`.  `swagger-tools` also has APIs for doing Swagger stuff but they have been deprecated in favor of [sway](https://github.com/apigee-127/sway), which is what `swagger-editor` uses.  This being said, `swagger-tools` might do more than `swagger-node` but the middleware doing the work for both are the same.
