### ISSUE TITLE
"Missing required property: schema"

### ISSUE THREAD

**Issue by mdujic00** [apigee-127/swagger-tools#461]
Hi,
I'm having an issue and can't find out what is missing. 

![image](https://cloud.githubusercontent.com/assets/11386465/21186662/ac196290-c215-11e6-9ba9-5ee18c1e8386.png)

**Comment by whitlockjc** [comment]
`swagger-ui` does not use `swagger-tools` _(is uses [sway](https://github.com/apigee-127/sway)) but since you're here, I'll help you out.  Your `_id` parameter is wrong.  Any time you have an `in: body`, it is expected to have a schema.  _(Look at the _"If in is body"_ section: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-7)_

Also, you should only have one `body` parameter: _"There can be one "body" parameter at most."_  That last part is a bug that needs to be fixed in sway, I'll report it.
