### ISSUE TITLE
When is the next version going out to npm?

### ISSUE THREAD

**Issue by killerham** [apigee-127/swagger-tools#482]
I need the nested controllers fix and was wondering when the next version is going out to npm. Is there any chance of getting a version bump?

**Comment by whitlockjc** [comment]
I'm not sure.  I really want to fix `json-refs` and once that's done, I'll come clean things up here.

**Comment by Osterjour** [comment]
There are some fixes here at Github since the last npm version. Would be nice to see at least those on npm - it doesn't make things worse than they are right now.
I assume you don't find the time regarding the `json-refs` @whitlockjc which is understandable, but maybe taking a few minutes to push the already merged fixes to npm might help some people here.

**Comment by whitlockjc** [comment]
`json-refs@v3.0.0` has been released and I'm now working on `swagger-tools` and `sway` updates.  Being only one person working on this, and having to make the time in my personal time, it's not always possible to find the time.  I apologize for the slowness but now that `json-refs` has been rewritten to fix accuracy/performance, the `swagger-tools` and `sway` updates should be soon.

**Comment by Osterjour** [comment]
No need to apologize - it's absolutely understandable! My intention was just to get was is already here, but if the updates are coming soon we can wait for it ;-)
Thanks!

**Comment by whitlockjc** [comment]
Within the next day.  Closing now since a release is imminent and this was more of a question than reporting a bug.
