### ISSUE TITLE
Does x-swagger-router-controller support typescript?

### ISSUE THREAD

**Issue by FieryCod** [apigee-127/swagger-tools#488]
Question same as in title. Can I point in . yaml  controllers to a  `ts` file and in operationId point to a function implemented in a 'ts' file? If so please tell me how to do it.

**Comment by whitlockjc** [comment]
I'm not sure honestly, I've never used TypeScript.  Maybe @rjnienaber or @liviuignat could help out.

**Comment by FieryCod** [comment]
@whitlockjc Finger crossed, hope that they could help me out. :)

**Comment by liviuignat** [comment]
hi @FieryCod , I patched swagger-tools to accept *.ts files and patched it to this npm package for now: https://www.npmjs.com/package/typescript-swagger-tools

Hope this helps.

**Comment by FieryCod** [comment]
Hi @liviuignat , did you propose it as a PR to swagger repo?

**Comment by rjnienaber** [comment]
@FieryCod, the problem was swagger-tools has a filter that looks for files with [a specific extension](https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-router.js#L68). I submitted [a pull request](https://github.com/apigee-127/swagger-tools/pull/473) that was merged, but this has not been published to npm yet. 

For my projects, I'm able to use a git hash to reference `swagger-tools` in my `package.json` e.g. 

```json
"swagger-tools": "git://github.com/apigee-127/swagger-tools#f759b8bb30d100a0a1ef743e77ce6676473485fa",
```

This works because all the machines have `git` installed when the dependencies are retrieved. In @liviuignat's case, he's using a docker image that does not have git installed which I believe is why he's published a separate package to npm.

**Comment by liviuignat** [comment]
@FieryCod , @rjnienaber explained it perfectly. I had to publish this to npm because it would had increase our Docker image size from 200MB to 500+MB by having git, gcc and other dependencies just to support git based dependencies. 

This reason alone was not acceptable for us.

**Comment by FieryCod** [comment]
Ok so as I can see swagger-tools and official swagger are different projects. I will report The issue to the official one. If the official swagger would not support .ts I'm gonna switch back to swagger-tools. Sory for the mess.

**Comment by whitlockjc** [comment]
No sweat.
