### ISSUE TITLE
Swagger Validates but not Starts

### ISSUE THREAD

**Issue by mKontakis** [apigee-127/swagger-tools#496]
I have a yaml reference like that:

`      responses:
        "200":
          description: Success
          schema:
            $ref: "test.yaml#/GetMoviesListResponse"`

Although swagger validates, it is denying to start:

![swagger-error](https://cloud.githubusercontent.com/assets/5832737/24911252/a23ee12a-1eca-11e7-9c69-f785fea3808c.PNG)

**Comment by whitlockjc** [comment]
Try running `swagger-tools validate YOUR_DOCUMENT` to see exactly what the validation failures are.  It looks like you've found a bug that will be fixed in #327 where the validation fails but no details are printed as expected.  I apologize.

I'm going to close this as a duplicate but feel free to continue the conversation if you need help fixing your invalid document.
