### ISSUE TITLE
nsp string vulnerability

### ISSUE THREAD

**Issue by Coosec** [apigee-127/swagger-tools#569]
There is vulnerability in string package:

`swagger-tools@0.10.3 > string@3.3.3`
https://nodesecurity.io/advisories/536

I noticed there is a change in master branch related to this vulnerability but when will you publish it on npm?

**Comment by thomasyuan** [comment]
Same question here. Can't pass CI cause by this issue.
When will we release next version?

**Comment by SpencerTuft** [comment]
Doesn't look like the stringjs repo is well maintained judging by the number of issues, pull requests and the recent commit history. The issue for stringjs vulnerability is [here](https://github.com/jprichardson/string.js/issues/212). I don't assume it will be fixed anytime soon.

**Comment by wombat86** [comment]
Hi! Any new on this?

**Comment by danyalaytekin** [comment]
Bump, seems quite urgent.

**Comment by wickedest** [comment]
Please fix urgently - npm install on any package using swagger-tools gets a high security alert.

**Comment by danyalaytekin** [comment]
Another month passes.

**Comment by whitlockjc** [comment]
Have you really looked into the scope of the `nsp` warning?  The [commit](https://github.com/apigee-127/swagger-tools/commit/857bf43c7809dae13a44bda4e56db92745d86fd4) that removes the dependency shows that the usage of `stringjs` in `swagger-tools` didn't even use the affected functions that could result in a DoS, and its use was limited to one `swagger-tools` CLI command: `info`  Chances are good you didn't even know that command existed, let alone actually using it.  This, along with the fact that `swagger-tools` is [deprecated](https://github.com/apigee-127/swagger-tools/issues/335), I just didn't see it being of the utmost importance.  My time is going into [sway](https://github.com/apigee-127/sway) and related tooling to completely EOL `swagger-tools` and the only effort that goes into it must be proven as necessary.  Given that I've looked into this, I really didnt' see it being that important since you could just as easily install `swagger-tools@master`.

I apologize if this comes of snarky.  If this is not good enough, feel free to offer to help run the project so things like this can get released.

**Comment by chrisEff** [comment]
Come on man. I get it, it's a deprecated project and you don't want to put any more effort in it, because you have something shiny and new...BUT:
Not everyone can just quickly migrate to sway since it doesn't seem to be backwards compatible to swagger-tools. And even though the vulnerable features from the string package are not actually being used, it's never a nice thing to have a high risk vulnerability alert in your dependencies. And having to do a deep check if you're REALLY affected by this can be very daunting, especially if swagger-tools is not the only one of your dependencies with an alert.
And all you have to do to make a lot of people happy is to publish a new version to npm, since the fix is already in master. That's a 5 minute task at max. It probably took you even longer to write that comment.
So PLEASE, would you do us that favor?

**Comment by whitlockjc** [comment]
`swagger-tools@0.10.4` released.
